// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbyuwjodymjurkzgvjof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJieXV3am9keW1qdXJremd2am9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczOTc1MTYsImV4cCI6MjA3Mjk3MzUxNn0.zJMCz1rzZXv8b5jq0-ZLbUiH8-3Ceyn-m83xJzAma40";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});